### obtener todas
GET http://localhost:3000/api/clients


#### obtener una 
GET http://localhost:3000/api/clients/2

### Cargar nueva 
POST http://localhost:3000/api/clients
Content-Type: application/json

{
  "name": "Wachin",
  "lastName":"Mega",
  "phoneNumber": 3412243123,
  "email": "wachincito@gmail.com",
  "dni": 1234,
  "status": false
}

#     name: req.body.name,
#     lastName: req.body.lastName,
#     phoneNumber: req.body.phoneNumber,
#     email: req.body.email,
#     dni: req.body.dni,

#     status: req.body.status

###modificar 
put http://localhost:3000/api/clients/2
Content-Type: application/json

  {
    "category": "PcGamer",
    "description": "Rtx 308011ti + Ryzen 7 5700x",
    "price": 10200,
    "pcNumber": 3,
    "status": true
  }

#### Eliminar 
delete http://localhost:3000/api/clients/1

