### obtener todas
GET http://localhost:3000/api/employees


#### obtener una 
GET http://localhost:3000/api/employees/MegamansitoWachin

### Cargar nueva 
POST http://localhost:3000/api/employees
Content-Type: application/json
x-role: admin
{
  "name": "Wachin",
  "lastName":"Super",
  "phoneNumber": 3412243123,
  "email": "wapi@gmail.com",
  "dni": 1234,
  "username": "wachincito123",
  "password": "wapi123"
}

#     name: req.body.name,
#     lastname: req.body.lastname,
#     phoneNumber: req.body.phoneNumber,
#     email: req.body.email,
#     dni: req.body.dni,

#     username: req.body.username,
#     password: req.body.password

###modificar 
PUT http://localhost:3000/api/employees/2
Content-Type: application/json
x-role: admin
 
{
  "name": "Wachincito",
  "lastName":"pequenin",
  "phoneNumber": "3471339081",
  "email": "wachincitopequenito@gmail.com",
  "dni": "1234", 
  "username": "wachincitopeque123",
  "password": "wachin"
}


#/*los toma como string a dni y number por eso los "" :  { "message": "Trying to set Employee.dni of type 'string' to '1234' of type 'number'" } */


#### Eliminar 
DELETE http://localhost:3000/api/employees/1

###Tryna log to work
POST  http://localhost:3000/api/employees/login
Content-Type: application/json

{
  "email": "wapi@gmail.com",
  "password": "wapi123"
}