### obtener computadoras
GET http://localhost:3000/api/computers


#### obtener una computadora
GET http://localhost:3000/api/computers/1

  # "maintenance": 0,
### Cargar nueva computadora
POST http://localhost:3000/api/computers
Content-Type: application/json

{
  "maintenance": 3,
  "category": 2,
  "status": "0",
  "description": "Rtx 3080ti + R1yzen 7 5700x",
  "pcNumber": 13
}

###modificar computadora
put http://localhost:3000/api/computers/2
Content-Type: application/json

  {
    "category": "PcGamer",
    "description": "Rtx 308011ti + Ryzen 7 5700x",
    "price": 10200,
    "pcNumber": 3,
    "status": true
  }

###modificar parcialmente computadora  Es innecesaria esta, despues lo saco.
PATCH http://localhost:3000/api/computers/2
Content-Type: application/json

  {
    "category": "PcGamer",
      "description": "Rtx 3080ti + Ryzen 7 5700x",
      "price": 1000,
      "pcNumber": 21,
      "status": false
  }
#### Eliminar computadora
delete http://localhost:3000/api/computers/1

