### ver computadoras disponibles para un turno
GET http://localhost:3000/api/turns/available-computers?date=2026-10-15&hour=10

### cargar nuevo turno
POST http://localhost:3000/api/turns
Content-Type: application/json

{
  "computerId": 1,
  "clientId": 3,
  "startTime": "2026-10-15T10:00:00.000Z",
  "endTime": "2026-10-15T11:00:00.000Z",
  "extraPrice": 0
}

### buscar una
GET http://localhost:3000/api/turns/2

### buscar todas
GET http://localhost:3000/api/turns

#### modificar
PATCH http://localhost:3000/api/turns/2
Content-Type: application/json

{
  "computerId": 3,
  "startTime": "2026-10-15T20:00:00.000Z",
  "endTime": "2026-10-15T21:00:00.000Z",
  "extraPrice": 0
}

#### eliminar
delete http://localhost:3000/api/turns/1
